[build]
  publish = "public"
  command = "hugo --gc --minify --templateMetrics --templateMetricsHints --source exampleSite --themesDir ../.."

[context.production.environment]
  HUGO_VERSION = "0.125.6"
