[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.. --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic"

[context.production.environment]
  HUGO_VERSION = "0.125.6"  # or another stable version supported by Netlify
